// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2B7ryC5xYq1lH3O6b-JspWgvYeVA2Ek',
    appId: '1:812009017286:web:c7dbc902a4f877c213ecc7',
    messagingSenderId: '812009017286',
    projectId: 'enter-21ee1',
    authDomain: 'enter-21ee1.firebaseapp.com',
    storageBucket: 'enter-21ee1.appspot.com',
    measurementId: 'G-1ZJKCWF36L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn0qoCkxhfFTgGB01_yBI6C1VAa4BDP60',
    appId: '1:812009017286:android:aa207d2d108b980c13ecc7',
    messagingSenderId: '812009017286',
    projectId: 'enter-21ee1',
    storageBucket: 'enter-21ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbABYBK4ZXB4ld9GNXn77Yz7DKTUKXQSw',
    appId: '1:812009017286:ios:383ffbff0e72fc5d13ecc7',
    messagingSenderId: '812009017286',
    projectId: 'enter-21ee1',
    storageBucket: 'enter-21ee1.appspot.com',
    iosBundleId: 'com.example.enterVideoStorageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbABYBK4ZXB4ld9GNXn77Yz7DKTUKXQSw',
    appId: '1:812009017286:ios:daa1ae5a7ab5838713ecc7',
    messagingSenderId: '812009017286',
    projectId: 'enter-21ee1',
    storageBucket: 'enter-21ee1.appspot.com',
    iosBundleId: 'com.example.enterVideoStorageApp.RunnerTests',
  );
}
